name: Publish to Pub.dev

on: 
  pull_request:
    types:
      - closed
    branches: 
      - master
jobs:
  publishing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!
      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{secrets.OAUTH_REFRESH_TOKEN }}
          skipTests: true
          force: true
    